from OOPsClass import Movie
movie1=Movie("LEO","Vijay","2023","Hit")
print(movie1.film)
print(movie1.hero)
print(movie1.year)
print(movie1.status)
movie1.ran()
movie1.ott()

movie2=Movie("Salaar","Prabhas","2024","Blockbuster")
print(movie2.film)
print(movie2.hero)
print(movie2.year)
print(movie2.status)
movie2.ran()
movie2.ott()